/**
 * This file was generated by bin2cpp v3.0.0
 * Copyright (C) 2013-2023 end2endzone.com. All rights reserved.
 * bin2cpp is open source software, see http://github.com/end2endzone/bin2cpp
 * Source code for file 'leaf_names.ewe', last modified 1716307184.
 * Do not modify this file.
 */
#pragma once
#include "EWGraphics/resources/common.h"

namespace bin2cpp
{
  const File & getLeaf_namesEweFile();
}; //bin2cpp
